//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int recipe_id { get; set; }
        public string recipe_name { get; set; }
        public string directions { get; set; }
        public int publics { get; set; }
        public string ingredients { get; set; }
        public string image_name { get; set; }
    }
}
